server:
  port: 9000
  servlet:
      context-path: /producer
spring:
  application:
    name: producer
eureka:
  client:
    service-url:
      defaultZone: http://172.18.82.41:10000/eureka/
  instance:
      ip-address: ture